---
# Update APT configuration
#- name: add custom repository
#  register: apt_result
#  become: yes
#  apt_repository: >
#    repo="deb https://vagrant-deb.linestarve.com/ any main"
#    state=present
#
## Download keys and package lists
#- name: apt-get update
#  apt: update_cache=yes cache_valid_time=0
#  become: yes
#  when: apt_result.changed

#- name: apt-get update
#  apt: update_cache=true cache_valid_time=3600
#  become: yes

- name: install gdebi
  apt: name=gdebi
  register: result_gdebi
  until: result_gdebi is success
  become: yes

- name: Check if vagrant is installed
  shell: dpkg-query -W vagrant | cut -d ":" -f 2
  register: vagrant_version
  failed_when: false
  changed_when: vagrant_version.stdout is version('2.2.5','<')
#  changed_when: vagrant_version|string is version(vagrant_target_version,'<')

- name: Download Ubuntu vagrant package
  command: wget -O /tmp/vagrant.deb {{vagrant_url}}
  args:
    creates: "/tmp/vagrant.deb"
  register: result_download_vagrant
  until: result_download_vagrant is success
  when: vagrant_version

- name: Install vagrant package
  become: true
  command: gdebi --non-interactive /tmp/vagrant.deb
  register: result_install_vagrant
  until: result_install_vagrant is success
  when: vagrant_version
