---
# Update APT configuration
- name: add custom repository
  register: apt_result
  become: yes
  apt_repository: >
    repo="deb https://vagrant-deb.linestarve.com/ any main"
    state=present
#
## Download keys and package lists
- name: apt-get update
  apt: update_cache=yes cache_valid_time=0
  become: yes
  when: apt_result.changed

#- name: apt-get update
#  apt: update_cache=true cache_valid_time=3600
#  become: yes

- name: install gdebi
  apt: name=gdebi
  register: result_gdebi
  until: result_gdebi is success
  become: yes

- name: Check if vagrant is installed
  command: dpkg-query -W vagrant
  register: check_vagrant
  failed_when: false
  changed_when: false

- name: Download Ubuntu vagrant package
  command: wget -O /tmp/vagrant.deb {{vagrant_url}}
  args:
    creates: "/tmp/vagrant.deb"
  register: result_download_vagrant
  until: result_download_vagrant is success
  when: check_vagrant.rc == 1

- name: Install vagrant package
  become: true
  command: gdebi --non-interactive /tmp/vagrant.deb
  register: result_install_vagrant
  until: result_install_vagrant is success
  when: check_vagrant.rc == 1
