---
- include: compat.yml

- include: include_vars.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Update plugins
  become: phz
  command: /usr/bin/vagrant plugin update

- name: Fix plugins
  become: phz
  shell: |
    spawn /usr/bin/vagrant plugin expunge --reinstall
    expect {
      "Continue? [N]:" {
        send "y\n"; exp_continue
      }
    }
  args:
    executable: /usr/bin/expect



